### ISSUE TITLE
Verbalizer: follow the prompt generation steps to verbalise the triples on this repository: https://github.com/helemanc/gryffindor

### ISSUE THREAD

**Issue by nikolas-rauscher** [nikolas-rauscher/ARDI-Scholarly-QALD#17]

**Comment by sefeoglu** [comment]
Hey @nikolas-rauscher , 
You need to fix the following code lines for the triples having same predicate
when the subjects or objects are same. For example, 
Triple list is :
```
paper 1 -> authored by  -> N. Rauscher
paper 2 -> authored by  -> N. Rauscher
paper 3 -> authored by  -> N. Rauscher
```
It will be like:
`{paper 1, paper 2 and paper 3}  -> authored by  -> N. Rauscher`

https://github.com/nikolas-rauscher/ARDI-Scholarly-QALD/blob/b320fd4a81d6fc780eb1938631c2b7ea7e1dc51c/src/models/verbalizer/generatePrompt.py#L18-L27
https://github.com/nikolas-rauscher/ARDI-Scholarly-QALD/blob/b320fd4a81d6fc780eb1938631c2b7ea7e1dc51c/src/models/verbalizer/generatePrompt.py#L5-L16

**Comment by sefeoglu** [comment]
done
