### ISSUE TITLE
Prompt Templates

### ISSUE THREAD

**Issue by nikolas-rauscher** [nikolas-rauscher/ARDI-Scholarly-QALD#18]

**Comment by sefeoglu** [comment]
Some pics from the conference: https://drive.google.com/drive/folders/1EuWR3hkqY9W38Z4VNPyCkLNTRLdrMFFg?usp=drive_link

**Comment by dendroenydris** [comment]
add an initial version [https://github.com/nikolas-rauscher/ARDI-Scholarly-QALD/commit/0e137134cc242ba549acaca5d080c223abdba0a7](0e13713)

**Comment by dendroenydris** [comment]
add an initial version in [0e13713](https://github.com/nikolas-rauscher/ARDI-Scholarly-QALD/commit/0e137134cc242ba549acaca5d080c223abdba0a7)

**Comment by sefeoglu** [comment]
You should change the following parameters:

prompt-> prompt_template
formatted_text -> prompt_text
formatted_texts - > prompt_dataset

`prompt = {"prompt": prompt_text, "answer":example["answer']}`

`prompt_dataset.append(prompt)`

```python
def formatting_prompts_func(prompt, example):
    """Create a list to store the formatted texts for each item in the example

    Args:
        example (list of dataset): one batch from dataset. each line might consist of prompt context and question
    Returns:
        formatted_texts: formated prompts
    """


    formatted_texts = []


    # Iterate through each example in the batch
    for context, question in zip(example['context'], example['question']):
        # Format each example as a prompt-response pair
        formatted_text = prompt.replace('[question]', question)
        formatted_text = prompt.replace('[context]', "Context: "+context)
        formatted_texts.append(formatted_text)
    # Return the list of formatted texts
    return formatted_texts
```
