### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by sefeoglu** [nikolas-rauscher/ARDI-Scholarly-QALD#20]
These requests cause time out.
The program should wait between the requests. Use following sleep after requests after the line 76 and 78
`time.sleep(3)`

https://github.com/nikolas-rauscher/ARDI-Scholarly-QALD/blob/25b84fc42e5cfcb2e8af837d055eb6283048addc/src/data/queries.py#L76-L78

**Comment by nikolas-rauscher** [comment]
I fixed it in  90c36ec9eea4802f3a9c3165996191d7bcb7f940
