### ISSUE TITLE
conserved_percentage on Evidence Selection

### ISSUE THREAD

**Issue by sefeoglu** [nikolas-rauscher/ARDI-Scholarly-QALD#39]
Hi @dendroenydris,
Can we set conserved_percentage to 0.01? since we have around 1000 triples/

Thanks.

https://github.com/nikolas-rauscher/ARDI-Scholarly-QALD/blob/6843a098da5728bafa6feb3590f6f1aeaa36c665/src/features/evidence_selection.py#L88

**Comment by dendroenydris** [comment]
Would it be better to set the maximum possible triple, for example, to 50?

**Comment by sefeoglu** [comment]
@dendroenydris Which parameters should I change?

**Comment by dendroenydris** [comment]
> @dendroenydris Which parameters should I change?

I've added the functionality and made a pull request. 
https://github.com/nikolas-rauscher/ARDI-Scholarly-QALD/pull/41

**Comment by sefeoglu** [comment]
I saw your pull request! Thanks.
